baseURL = 'https://cristobal.liendo.net'
languageCode = 'en-us'
title = 'Cristobal Liendo'
enableRobotsTXT = true
[menus]
    [[menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10
    [[menus.main]]
        name = 'Blog'
        pageRef = '/blog/'
        weight = 20